%{?!ros_distro:%global ros_distro rolling}
%global pkg_name menge_vendor
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-rolling-menge-vendor
Version:        1.3.0
Release:        2%{?dist}
Summary:        ROS %{pkg_name} package

License:        Apache 2.0
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%{?bloom_package}

%description
Menge is a powerful, cross-platform, modular framework for crowd simulation
developed at the University of North Carolina - Chapel Hill. This package
includes the core simulation part of origin menge package, with a bit
modification for crowd simulation in gazebo and ignition gazebo.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
Menge is a powerful, cross-platform, modular framework for crowd simulation
developed at the University of North Carolina - Chapel Hill. This package
includes the core simulation part of origin menge package, with a bit
modification for crowd simulation in gazebo and ignition gazebo.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
Menge is a powerful, cross-platform, modular framework for crowd simulation
developed at the University of North Carolina - Chapel Hill. This package
includes the core simulation part of origin menge package, with a bit
modification for crowd simulation in gazebo and ignition gazebo.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
    -DCATKIN_ENABLE_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Tue Apr 28 2026 Shao Guoliang <fredshao@openrobotics.org> - 1.3.0-2
- Autogenerated by Bloom

* Tue Apr 21 2026 Shao Guoliang <fredshao@openrobotics.org> - 1.3.0-1
- Autogenerated by Bloom
